<p><b>课文笔记</b></p>
<div class="block">
	<?php template_list([
		'an expedition to…去……的探险',
		'explorer n.探险家',
		'It was considered a great honour to do sth. 被认为做某事是极大的荣誉',
		'Below are/is….  以下是……(方位副词放句首，句子完全倒装)',
		'It happened that…  碰巧……',
		'dream of  梦想',
		'be ready for  为……做好准备',
		'at the age of在……岁时',
		'fit adj.健康的',
		'full of vigour 充满活力',
		'full of vigour 充满活力',
		'apply to do sth.申请做某事',
		'go along with与……一起',
		'go aboard the ship上船',
		'set off出发',
		'turn back往回走',
		'assign sb. to do sth.分派某人做某事',
		'become stuck in陷入……',
		'well and truly彻底地',
		'throw away扔掉',
		'keep one’s spirits up让某人情绪高涨',
		'manage to do sth.设法做某事',
		'from bad to worse越来越糟',
		'on the shore of在……岸边',
		'make it到达，成功',
		'be interrupted by被……打断',
		'PLA=People’s Liberation Army 中国人民解放军—海军',
		'Bringing up 抚养',
		'Ground Force 陆军',
		'Air Force 空军',
		'Idol n.偶像',
		'Streetcar 有轨电车',
		'Sobbed bitterly 痛苦',
		'Streamed v.流动 n.小河',
		'Top-class 一流的',
		'Promising 有前途的',
		'Essential 基本的',
		'Filling out 填写',
		'Forms 表格',
		'Register 注册',
		'Knack 本领',
		'Draw up 起草',
		'Oasis 绿洲',
		'Finalize 最终确定',
		'Manufacturer 生产者',
		'Accelerate production加速生产',
		'free yourself from   把某人从…中解救出来',
		'do great damage to  对……造成极大伤害',
		'make it到达，成功',
		'be interrupted by被……打断',
		'hold on坚持住',
		'turn into转变，变成',
		'one’s concern for某人对……的关心',
		'fill…with…用……填满……',
		'There is a chance that…有机会……',
		'after all毕竟',
		'continuation n.叙篇',
		'the reward for……的回报',
		'ahead of在……前面',
		'sth. happened to sb.某人发生了某事',
		'What if要是……怎么样呢?',
		'There is/was nothing like …',
		'cheer sb. up使某人振奋起来没有什么比……更……(表达赞美句型)',
		'fall into陷入',
		'oily adj.油腻的，含油的',
		'note v.记录',
		'be bored with对……厌倦=be fed up with=be tired of',
		'pretty well几乎',
		'was highly thought of in 被高度评价',
		'on a regular basis 定期',
		'rewarded n.消遣',
		'pastime 休闲活动',
		'rewarding 值得做的',
		'Digging through 挖掘',
		'Tiger Parents Do No Good to Kid’s Development告诉家长不要过分参与孩子的学习，要让他们在错误中成长',
		'be responsible for 对…负责',
		'settled down 安定下来',
		'find out 发现、发明',
		'flat n.公寓',
		'preserve your dignity   保持你的尊严',
		'the opening speeches   开幕词',
		'laboratory   n.实验室',
		'declare  v.==>declaration   n.宣布',
		'calculate  v.==>calculation  n.计算',
		'deny   v.否认;拒绝',
		'How did it come about that…. ……怎么发生的',
		'the accused   被告',
		'postpone  v.推迟',
		'make oneself done 使某人自己被……',
		'reaction to 对……的反应',
		'find   it   adj. to do 发现做某事……',
		'get through   to   sb. (电话)打通……',
		'promote   v.  促进',
		'resume writing  写简历',
		'respondent  n.  调查对象',
		'compulsory adj.  必修的',
		'domestic tasks  家务琐事',
		'curriculum   n.课程',
		'endure  v.容忍==> endurance  n. 忍耐力',
		'vigour n.精力==>vigorous adj.充满活力的'
	]); ?>
</div>
<div class="block block-pink">
	<?php template_list([
		'labour   n.劳动 vi.努力工作 labour for为……而努力工作 manual labour 体力劳动 labour to do 努力做',
		'grip v.紧握 grip hands紧紧握手 grip  the rope抓紧绳子 grip one’s attention吸引某人的注意力',
		'hazy adj.模糊的，朦胧的 a hazy memory模糊的记忆 a hazy idea模糊的概念 go hazy变得模糊',
		'fetch vt.去拿来 fetch sb. sth.为某人拿来某物 fetch sth. for sb.为某人拿来某物 fetch a doctor 去请医生',
		'turn out 结果是 turn over  翻转,移交 turn to  转向，翻到，求助于 turn in上交 turn up出现;露面，开大音量 turn down拒绝，调低音量',
		'pace n.步伐 at a…pace  以……速度 keep pace with  与……并驾齐驱',
		'fall away逐渐减少，消失 fall back后退，撤退 fall behind落后 fall down掉下，跌倒',
		'division n.分开 divide vt .除以; 使分开;分隔 a division of  …….的分歧',
		'urge v.催促 urgent adj. 紧迫的；紧急的 urgency n. 紧迫；急迫 have an urge to do sth.有做某事的欲望 urge sb. to do /into doing sth.催促某人做某事 urge that …should do sth. 极力主张…… It is urged that …should do sth.极力主张……',
		'random adj.随机的 randomly adv.随便地 at random随便地',
		'maximum n.最大量 minimum  n.最小量 a maximum of 最多 up to a maximum of $1000 最高达1000美元',
		'explode v.爆炸 explosion   n.爆炸，激增 explode into laughter突然大笑起来 explode with anger勃然大怒',
		'jolt v.震动 be jolted by被……震惊 a sudden jolt突然一震',
		'flip v.使快速翻转 flip over翻转',
		'stun vt.使震惊 stunning  adj.令人震惊的',
		'表示“吃惊的”的词 astonishing、surprising、shocking',
		'mud n.泥浆 muddy adj.泥泞的'
	])?>
</div>
